/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        // New color palette
        dark: 'var(--color-oxidized-iron-950)',
        primary: 'var(--color-oxidized-iron-500)',
        accent: 'var(--color-golden-orange-500)',
        neon: 'var(--color-mint-leaf-500)',
        cyan: 'var(--color-pacific-cyan-500)',
        khaki: 'var(--color-dark-khaki-500)',
        // Full palettes
        iron: {
          50: 'var(--color-oxidized-iron-50)',
          100: 'var(--color-oxidized-iron-100)',
          200: 'var(--color-oxidized-iron-200)',
          300: 'var(--color-oxidized-iron-300)',
          400: 'var(--color-oxidized-iron-400)',
          500: 'var(--color-oxidized-iron-500)',
          600: 'var(--color-oxidized-iron-600)',
          700: 'var(--color-oxidized-iron-700)',
          800: 'var(--color-oxidized-iron-800)',
          900: 'var(--color-oxidized-iron-900)',
          950: 'var(--color-oxidized-iron-950)',
        },
        orange: {
          50: 'var(--color-golden-orange-50)',
          100: 'var(--color-golden-orange-100)',
          200: 'var(--color-golden-orange-200)',
          300: 'var(--color-golden-orange-300)',
          400: 'var(--color-golden-orange-400)',
          500: 'var(--color-golden-orange-500)',
          600: 'var(--color-golden-orange-600)',
          700: 'var(--color-golden-orange-700)',
          800: 'var(--color-golden-orange-800)',
          900: 'var(--color-golden-orange-900)',
          950: 'var(--color-golden-orange-950)',
        },
        mint: {
          50: 'var(--color-mint-leaf-50)',
          100: 'var(--color-mint-leaf-100)',
          200: 'var(--color-mint-leaf-200)',
          300: 'var(--color-mint-leaf-300)',
          400: 'var(--color-mint-leaf-400)',
          500: 'var(--color-mint-leaf-500)',
          600: 'var(--color-mint-leaf-600)',
          700: 'var(--color-mint-leaf-700)',
          800: 'var(--color-mint-leaf-800)',
          900: 'var(--color-mint-leaf-900)',
          950: 'var(--color-mint-leaf-950)',
        },
        pacific: {
          50: 'var(--color-pacific-cyan-50)',
          100: 'var(--color-pacific-cyan-100)',
          200: 'var(--color-pacific-cyan-200)',
          300: 'var(--color-pacific-cyan-300)',
          400: 'var(--color-pacific-cyan-400)',
          500: 'var(--color-pacific-cyan-500)',
          600: 'var(--color-pacific-cyan-600)',
          700: 'var(--color-pacific-cyan-700)',
          800: 'var(--color-pacific-cyan-800)',
          900: 'var(--color-pacific-cyan-900)',
          950: 'var(--color-pacific-cyan-950)',
        },
        earth: {
          50: 'var(--color-dark-khaki-50)',
          100: 'var(--color-dark-khaki-100)',
          200: 'var(--color-dark-khaki-200)',
          300: 'var(--color-dark-khaki-300)',
          400: 'var(--color-dark-khaki-400)',
          500: 'var(--color-dark-khaki-500)',
          600: 'var(--color-dark-khaki-600)',
          700: 'var(--color-dark-khaki-700)',
          800: 'var(--color-dark-khaki-800)',
          900: 'var(--color-dark-khaki-900)',
          950: 'var(--color-dark-khaki-950)',
        },
      },
      fontFamily: {
        sans: ['var(--font-outfit)', 'system-ui', 'sans-serif'],
        josefin: ['var(--font-josefin)', 'serif'],
        mono: ['Courier New', 'Courier', 'monospace'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
